import { createContext, useContext, useState } from 'react'

const LangContext = createContext()

const translations = {
  es: {
    navFeatures: 'Funciones',
    navHow: '¿Cómo funciona?',
    navPricing: 'Precios',
    navContact: 'Contacto',
    navCta: 'Descargar gratis',
    heroBadge: 'Ya disponible en Google Play',
    heroTitle: 'Tu familia,',
    heroAccent: 'siempre conectada.',
    heroSub: 'Mensajes, ubicación en tiempo real y alertas de emergencia automáticas. CheckOK es la app de seguridad familiar que actúa cuando más lo necesitas.',
    heroPlayStore: 'Google Play',
    heroSeeFeatures: 'Ver funciones →',
    statCoverage: 'Cobertura',
    statAlert: 'Alerta push',
    statBackup: 'Email backup',
    phoneLive: 'EN VIVO',
    phoneAlert: 'ALERTA DE EMERGENCIA',
    phoneAlertSub: 'Valeria no respondió • hace 2 min',
    phoneFamily: 'Mi Familia',
    phoneMessages: 'Mensajes',
    phoneMsg1: 'Ya llegué al trabajo ✓',
    phoneMsg2: 'Ok! Cuídate 💙',
    badgeEmail: 'Email enviado',
    badgeEmailSub: 'Backup activado',
    badgeGps: 'Ubicación activa',
    badgeGpsSub: 'GPS en tiempo real',
    featuresLabel: 'Funcionalidades',
    featuresTitle: 'Todo lo que necesitas,\nen una sola app.',
    featuresSub: 'CheckOK combina mensajería, geolocalización y alertas automáticas para que nunca pierdas el rastro de quienes más quieres.',
    screenshotsLabel: 'Capturas',
    screenshotsTitle: 'Diseñada para el uso diario.',
    screenshotsSub: 'Una interfaz limpia, intuitiva y segura. Sin curva de aprendizaje para ningún miembro de tu familia.',
    sc1: 'Pantalla principal', sc2: 'Mapa en tiempo real', sc3: 'Chat familiar', sc4: 'Alerta activa', sc5: 'Configuración',
    howLabel: 'Cómo funciona',
    howTitle: 'Listo en minutos.',
    howSub: 'Sin configuraciones complicadas. Tu familia protegida en 4 pasos simples.',
    step1Title: 'Descarga la app', step1: 'Disponible en Google Play, gratis para siempre con plan Lite.',
    step2Title: 'Crea tu grupo', step2: 'Registra tu familia y comparte el código de invitación único.',
    step3Title: 'Configura alertas', step3: 'Define el tiempo de respuesta y quién recibe las notificaciones de emergencia.',
    step4Title: 'Tranquilidad total', step4: 'CheckOK cuida a tu familia en segundo plano, 24/7, sin que tengas que hacer nada.',
    emergencyLabel: 'Sistema de emergencias',
    emergencyTitle: 'Actúa antes de\nque sea tarde.',
    emergencySub: 'Nuestro sistema de alertas en cascada garantiza que la notificación llegue, aunque falle el internet o el teléfono esté en silencio.',
    em1: 'Push notification vía Firebase FCM',
    em2: 'Email de respaldo automático vía Resend',
    em3: 'Coordenadas GPS incluidas en la alerta',
    em4: 'Tiempo de respuesta configurable (5–60 min)',
    emActive: 'ALERTA ACTIVA', emSim: 'Simulación en vivo',
    emStep1Title: 'Check-in no respondido', emStep1: 'Valeria tenía 15 min para confirmar. Timer expirado.',
    emStep2Title: 'Push enviado', emStep2: 'Notificación a todos los miembros del grupo vía FCM.',
    emStep3Title: 'Email de respaldo', emStep3: 'Enviado automáticamente con coordenadas GPS incluidas.',
    emStep4Title: 'Familia notificada', emStep4: 'Todos saben dónde está y pueden actuar de inmediato.',
    pricingLabel: 'Planes',
    pricingTitle: 'Simple y transparente.',
    pricingSub: 'Empieza gratis, actualiza cuando quieras. Sin suscripciones sorpresa.',
    liteDesc: 'Para familias pequeñas que quieren empezar a cuidarse.',
    liteFeatures: ['Hasta 3 miembros', 'Mensajería básica', 'Alertas de emergencia', '1 tema visual'],
    liteBtn: 'Descargar gratis',
    recommended: 'Recomendado',
    proDesc: 'Para familias que quieren protección completa y sin límites.',
    proFeatures: ['Miembros ilimitados', 'Geolocalización en vivo', 'Email backup de alertas', '3 temas visuales', 'Check-in automático', 'Soporte prioritario'],
    proBtn: 'Empezar Pro',
    perMonth: '/ mes',
    forever: '/ siempre',
    contactLabel: 'Contacto',
    contactTitle: '¿Tienes alguna pregunta?',
    contactSub: 'Estamos en beta cerrada. Si quieres unirte a las pruebas o tienes feedback, escríbenos.',
    contactPlayStore: 'Google Play — Beta cerrada',
    labelName: 'Nombre', labelEmail: 'Email', labelMessage: 'Mensaje',
    sendBtn: 'Enviar →',
    footerMade: 'Hecho con ♥ en México.',
    footerPrivacy: 'Privacidad',
  },
  en: {
    navFeatures: 'Features',
    navHow: 'How it works',
    navPricing: 'Pricing',
    navContact: 'Contact',
    navCta: 'Download free',
    heroBadge: 'Now on Google Play',
    heroTitle: 'Your family,',
    heroAccent: 'always connected.',
    heroSub: 'Messages, real-time location and automatic emergency alerts. CheckOK is the family safety app that acts when you need it most.',
    heroPlayStore: 'Google Play',
    heroSeeFeatures: 'See features →',
    statCoverage: 'Coverage',
    statAlert: 'Push alert',
    statBackup: 'Email backup',
    phoneLive: 'LIVE',
    phoneAlert: 'EMERGENCY ALERT',
    phoneAlertSub: "Valeria didn't respond • 2 min ago",
    phoneFamily: 'My Family',
    phoneMessages: 'Messages',
    phoneMsg1: 'I got to work ✓',
    phoneMsg2: 'Ok! Take care 💙',
    badgeEmail: 'Email sent',
    badgeEmailSub: 'Backup activated',
    badgeGps: 'Location active',
    badgeGpsSub: 'Real-time GPS',
    featuresLabel: 'Features',
    featuresTitle: 'Everything you need,\nin one app.',
    featuresSub: 'CheckOK combines messaging, geolocation and automatic alerts so you never lose track of the ones you love most.',
    screenshotsLabel: 'Screenshots',
    screenshotsTitle: 'Designed for daily use.',
    screenshotsSub: 'A clean, intuitive and secure interface. No learning curve for any family member.',
    sc1: 'Home screen', sc2: 'Real-time map', sc3: 'Family chat', sc4: 'Active alert', sc5: 'Settings',
    howLabel: 'How it works',
    howTitle: 'Ready in minutes.',
    howSub: 'No complex setup. Your family protected in 4 simple steps.',
    step1Title: 'Download the app', step1: 'Available on Google Play, free forever with the Lite plan.',
    step2Title: 'Create your group', step2: 'Register your family and share the unique invitation code.',
    step3Title: 'Set up alerts', step3: 'Define response time and who receives emergency notifications.',
    step4Title: 'Total peace of mind', step4: "CheckOK takes care of your family in the background, 24/7, without you having to do anything.",
    emergencyLabel: 'Emergency system',
    emergencyTitle: "Acts before\nit's too late.",
    emergencySub: 'Our cascade alert system guarantees the notification gets through, even if the internet fails or the phone is on silent.',
    em1: 'Push notification via Firebase FCM',
    em2: 'Automatic email backup via Resend',
    em3: 'GPS coordinates included in the alert',
    em4: 'Configurable response time (5–60 min)',
    emActive: 'ACTIVE ALERT', emSim: 'Live simulation',
    emStep1Title: 'Check-in not responded', emStep1: 'Valeria had 15 min to confirm. Timer expired.',
    emStep2Title: 'Push sent', emStep2: 'Notification to all group members via FCM.',
    emStep3Title: 'Backup email', emStep3: 'Sent automatically with GPS coordinates included.',
    emStep4Title: 'Family notified', emStep4: 'Everyone knows where they are and can act immediately.',
    pricingLabel: 'Plans',
    pricingTitle: 'Simple and transparent.',
    pricingSub: 'Start free, upgrade whenever. No surprise subscriptions.',
    liteDesc: 'For small families who want to start taking care of each other.',
    liteFeatures: ['Up to 3 members', 'Basic messaging', 'Emergency alerts', '1 visual theme'],
    liteBtn: 'Download free',
    recommended: 'Recommended',
    proDesc: 'For families who want complete, unlimited protection.',
    proFeatures: ['Unlimited members', 'Live geolocation', 'Alert email backup', '3 visual themes', 'Automatic check-in', 'Priority support'],
    proBtn: 'Start Pro',
    perMonth: '/ month',
    forever: '/ forever',
    contactLabel: 'Contact',
    contactTitle: 'Have a question?',
    contactSub: "We're in closed beta. If you want to join the tests or have feedback, write to us.",
    contactPlayStore: 'Google Play — Closed beta',
    labelName: 'Name', labelEmail: 'Email', labelMessage: 'Message',
    sendBtn: 'Send →',
    footerMade: 'Made with ♥ in Mexico.',
    footerPrivacy: 'Privacy',
  }
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState('es')
  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
